### ISSUE TITLE
Annotation export for at least some formats should be per-kind

### ISSUE THREAD

**Issue by bethac07** [piximi/piximi-beta#7]
**Is your feature request related to a problem? Please describe.**
While beta fixes at least several of the broken annotation exports described in piximi/piximi#528 (I didn't try literally all of them, but all the ones I did try worked!), if you have multiple kinds in an image (as we do in the example image), in the annotation export all the kinds are mixed together. This is I presume preferred for json-based export formats, but makes it impossible to separate ie nuclei and cells in the image-based formats. 

**Describe the solution you'd like**
For image-type exports (rather than text exports), annotations should be exported independently per kind

**Comment by gnodar01** [comment]
Much, but not all, of the issues now documented in piximi/piximi#528 stem from this issue. Fixing this will fix the vast majority there, so closing this as redundant, since that is already on the project board as well.
