### ISSUE TITLE
Users should be able to run multiple segmentation models on the same image

### ISSUE THREAD

**Issue by bethac07** [piximi/piximi-beta#9]
In beta (because I wanted to use the new gland model), I tried to run first the Stardist model on some test data to find nuclei, then run the gland model to find glands. When I try to run that model, though, I get the message that "No unlabeled images to predict". Since each segmentation model makes its own `kind`, we should be able to run them sequentially.

**Comment by Andrea-Papaleo** [comment]
Would it make sense to prepend kind names generated by the model with the model name? 

For instance if using stardist it would make "stardist_nucleus", or something to that effect.

I could see a use case if for instance if a user wants to compare two models.

**Comment by bethac07** [comment]
I like that idea a lot!
